const TASK_STATES = {
  PENDING: "PENDING",
  PLANNING: "PLANNING",
  EXECUTING: "EXECUTING",
  RETRYING: "RETRYING",
  SUCCEEDED: "SUCCEEDED",
  FAILED: "FAILED",
  CRASHED: "CRASHED",
};

module.exports = TASK_STATES;
